// Program IDL - Generated by Anchor
// Update this with your actual IDL after running `anchor build`

export const IDL = {
  version: "0.1.0",
  name: "memecoin_staking",
  instructions: [
    {
      name: "initializePool",
      accounts: [
        { name: "authority", isMut: true, isSigner: true },
        { name: "pool", isMut: true, isSigner: false },
        { name: "stakingMint", isMut: false, isSigner: false },
        { name: "rewardMint", isMut: false, isSigner: false },
        { name: "poolVault", isMut: true, isSigner: false },
        { name: "rewardVault", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        { name: "rewardRate", type: "u64" },
        { name: "lockPeriod", type: "i64" },
      ],
    },
    {
      name: "stake",
      accounts: [
        { name: "user", isMut: true, isSigner: true },
        { name: "pool", isMut: true, isSigner: false },
        { name: "userStake", isMut: true, isSigner: false },
        { name: "userTokenAccount", isMut: true, isSigner: false },
        { name: "poolVault", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "unstake",
      accounts: [
        { name: "user", isMut: true, isSigner: true },
        { name: "pool", isMut: true, isSigner: false },
        { name: "userStake", isMut: true, isSigner: false },
        { name: "userTokenAccount", isMut: true, isSigner: false },
        { name: "poolVault", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "claimRewards",
      accounts: [
        { name: "user", isMut: true, isSigner: true },
        { name: "pool", isMut: false, isSigner: false },
        { name: "userStake", isMut: true, isSigner: false },
        { name: "userRewardAccount", isMut: true, isSigner: false },
        { name: "rewardVault", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "updateRewardRate",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "pool", isMut: true, isSigner: false },
      ],
      args: [{ name: "newRate", type: "u64" }],
    },
    {
      name: "setPaused",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "pool", isMut: true, isSigner: false },
      ],
      args: [{ name: "paused", type: "bool" }],
    },
    {
      name: "fundRewards",
      accounts: [
        { name: "funder", isMut: true, isSigner: true },
        { name: "pool", isMut: false, isSigner: false },
        { name: "funderTokenAccount", isMut: true, isSigner: false },
        { name: "rewardVault", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "StakePool",
      type: {
        kind: "struct",
        fields: [
          { name: "authority", type: "publicKey" },
          { name: "stakingMint", type: "publicKey" },
          { name: "rewardMint", type: "publicKey" },
          { name: "poolVault", type: "publicKey" },
          { name: "rewardVault", type: "publicKey" },
          { name: "rewardRate", type: "u64" },
          { name: "lockPeriod", type: "i64" },
          { name: "totalStaked", type: "u64" },
          { name: "lastUpdateTime", type: "i64" },
          { name: "paused", type: "bool" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "UserStake",
      type: {
        kind: "struct",
        fields: [
          { name: "owner", type: "publicKey" },
          { name: "pool", type: "publicKey" },
          { name: "stakedAmount", type: "u64" },
          { name: "pendingRewards", type: "u64" },
          { name: "lastStakeTime", type: "i64" },
          { name: "stakeStartTime", type: "i64" },
          { name: "totalRewardsClaimed", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  events: [
    {
      name: "PoolInitialized",
      fields: [
        { name: "pool", type: "publicKey", index: false },
        { name: "stakingMint", type: "publicKey", index: false },
        { name: "rewardMint", type: "publicKey", index: false },
        { name: "rewardRate", type: "u64", index: false },
        { name: "lockPeriod", type: "i64", index: false },
      ],
    },
    {
      name: "StakeEvent",
      fields: [
        { name: "user", type: "publicKey", index: false },
        { name: "pool", type: "publicKey", index: false },
        { name: "amount", type: "u64", index: false },
        { name: "totalStaked", type: "u64", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "UnstakeEvent",
      fields: [
        { name: "user", type: "publicKey", index: false },
        { name: "pool", type: "publicKey", index: false },
        { name: "amount", type: "u64", index: false },
        { name: "remainingStake", type: "u64", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "ClaimEvent",
      fields: [
        { name: "user", type: "publicKey", index: false },
        { name: "pool", type: "publicKey", index: false },
        { name: "amount", type: "u64", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: "InvalidAmount", msg: "Invalid stake amount - must be greater than 0" },
    { code: 6001, name: "InsufficientStake", msg: "Insufficient staked balance" },
    { code: 6002, name: "StillLocked", msg: "Tokens are still in lock period" },
    { code: 6003, name: "NoRewards", msg: "No rewards available to claim" },
    { code: 6004, name: "PoolPaused", msg: "Pool is currently paused" },
    { code: 6005, name: "InsufficientRewardBalance", msg: "Insufficient reward tokens in vault" },
    { code: 6006, name: "MathOverflow", msg: "Math overflow error" },
    { code: 6007, name: "Unauthorized", msg: "Unauthorized - admin only" },
    { code: 6008, name: "InvalidOwner", msg: "Invalid token account owner" },
    { code: 6009, name: "InvalidMint", msg: "Invalid token mint" },
  ],
};

export type MemecoinStaking = typeof IDL;

